LOG_DIR: 'logs/baseline'
EXP_NAME: 'hmr_baseline'
SEED_VALUE: -1
METHOD: 'baseline'
RUN_TEST: False
PROJECT_NAME: 'mp2022'
DATASET:
  LOAD_TYPE: 'Base'
  BATCH_SIZE: 64
  NUM_WORKERS: 16
  PIN_MEMORY: True
  SHUFFLE_TRAIN: True
  TRAIN_DS: 'all'
  VAL_DS: '3dpw-val'
  NUM_IMAGES: -1
  IMG_RES: 128
OPTIMIZER:
  TYPE: 'adam'
  LR: 5e-5
  WD: 0.0
TRAINING:
  RESUME: null
  PRETRAINED: null
  PRETRAINED_LIT: null
  MAX_EPOCHS: 1
  SAVE_IMAGES: True
  LOG_SAVE_INTERVAL: 50
  LOG_FREQ_TB_IMAGES: 2000
  CHECK_VAL_EVERY_N_EPOCH: 1
  RELOAD_DATALOADERS_EVERY_EPOCH: True
HMR:
  SHAPE_LOSS_WEIGHT: 0
  KEYPOINT_LOSS_WEIGHT: 5.
  KEYPOINT_NATIVE_LOSS_WEIGHT: 5.
  POSE_LOSS_WEIGHT: 1.
  BETA_LOSS_WEIGHT: 0.001
  OPENPOSE_TRAIN_WEIGHT: 0.
  GT_TRAIN_WEIGHT: 1.
  LOSS_WEIGHT: 60.
TESTING:
  SAVE_IMAGES: false
  SIDEVIEW: true