LOG_DIR: 'logs/pare'
EXP_NAME: 'hmr_pare'
SEED_VALUE: -1
METHOD: 'pare'
RUN_TEST: False
PROJECT_NAME: 'mp2022'
DATASET:
  FOCAL_LENGTH: 5000.0
  LOAD_TYPE: 'Base'
  BATCH_SIZE: 64
  NUM_WORKERS: 16
  PIN_MEMORY: True
  SHUFFLE_TRAIN: True
  TRAIN_DS: 'all'
  VAL_DS: '3dpw-val'
  NUM_IMAGES: -1
  IMG_RES: 224
  USE_HEATMAPS: part_segm
OPTIMIZER:
  TYPE: 'adam'
  LR: 5e-5
  WD: 0.0
TRAINING:
  RESUME: null
  PRETRAINED: null
  PRETRAINED_LIT: null
  MAX_EPOCHS: 100
  SAVE_IMAGES: True
  LOG_SAVE_INTERVAL: 50
  LOG_FREQ_TB_IMAGES: 2000
  CHECK_VAL_EVERY_N_EPOCH: 1
  RELOAD_DATALOADERS_EVERY_EPOCH: True
HMR:
  SHAPE_LOSS_WEIGHT: 0
  KEYPOINT_LOSS_WEIGHT: 5.
  KEYPOINT_NATIVE_LOSS_WEIGHT: 5.
  POSE_LOSS_WEIGHT: 1.
  BETA_LOSS_WEIGHT: 0.001
  OPENPOSE_TRAIN_WEIGHT: 0.
  GT_TRAIN_WEIGHT: 1.
  LOSS_WEIGHT: 60.
TESTING:
  SAVE_IMAGES: false
  SIDEVIEW: true
PARE:
  BACKBONE: resnet50
  SHAPE_LOSS_WEIGHT: 0
  KEYPOINT_LOSS_WEIGHT: 5.
  KEYPOINT_NATIVE_LOSS_WEIGHT: 5.
  POSE_LOSS_WEIGHT: 1.
  BETA_LOSS_WEIGHT: 0.001
  OPENPOSE_TRAIN_WEIGHT: 0.
  GT_TRAIN_WEIGHT: 1.
  LOSS_WEIGHT: 60.
  NUM_JOINTS: 24
  SOFTMAX_TEMP: 1.0
  NUM_ITERATIONS: 3
  USE_UPSAMPLING: true
  DECONV_CONV_KERNEL_SIZE: 3
  NUM_DECONV_LAYERS: 3
  NUM_DECONV_FILTERS: 256
  NUM_FEATURES_SMPL: 64
  NUM_JOINTS: 24
  USE_KEYPOINT_ATTENTION: true
  USE_POSTCONV_KEYPOINT_ATTENTION: false
  KEYPOINT_ATTENTION_ACT: softmax
  USE_SCALE_KEYPOINT_ATTENTION: false
  SHAPE_MLP_NUM_LAYERS: 1
  POSE_MLP_NUM_LAYERS: 1